// Public runtime config validator.
//
// The Supabase client itself (`src/integrations/supabase/client.ts`) is
// auto-generated by Lovable Cloud and intentionally embeds the publishable
// URL + anon key — those are public-by-design and safe in the bundle.
//
// This module exists so the rest of the app can read those values through a
// single validated surface and fail loudly (instead of silently rendering a
// broken UI) if Lovable Cloud ever stops injecting them.
//
// IMPORTANT: never read or expose service-role keys, provider API keys, or
// any server-side secret from the frontend. Those live in Edge Function env.

const SUPABASE_URL = "https://sacxoanuyetjfrfllkzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhY3hvYW51eWV0amZyZmxsa3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc1NzU0MTIsImV4cCI6MjA5MzE1MTQxMn0.QRgtAVJjNMLN8-Lsdxj4_DlooWkNBjcqu92cizwpIlY";

// Prefer Vite env when present (forward-compatible), fall back to the
// generated constants so behavior is unchanged today.
const envUrl =
  (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_URL) || SUPABASE_URL;
const envKey =
  (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
  (typeof import.meta !== "undefined" && (import.meta as any).env?.VITE_SUPABASE_ANON_KEY) ||
  SUPABASE_PUBLISHABLE_KEY;

export const publicEnv = Object.freeze({
  SUPABASE_URL: String(envUrl),
  SUPABASE_PUBLISHABLE_KEY: String(envKey),
});

export function getEnvConfigError(): string | null {
  if (!publicEnv.SUPABASE_URL || !/^https:\/\//.test(publicEnv.SUPABASE_URL)) {
    return "Backend URL is missing or invalid. Please contact support.";
  }
  if (!publicEnv.SUPABASE_PUBLISHABLE_KEY || publicEnv.SUPABASE_PUBLISHABLE_KEY.length < 20) {
    return "Backend publishable key is missing. Please contact support.";
  }
  return null;
}
